name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # Needed for test reporting

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Run Backend Tests
      run: |
        cd demo
        ./gradlew test -Pspring.profiles.active=nodb

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: demo/build/test-results/**/*.xml

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      if: always()
      with:
        jacoco-csv-file: demo/build/reports/jacoco/test/jacocoTestReport.csv
        badges-directory: .github/badges
        generate-branches-badge: true
        generate-summary: true

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: jacoco-report
        path: demo/build/reports/jacoco/test/html/
