name: Vue app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
        working-directory: frontend 
      - run: npm install --save-dev @types/lodash-es
        working-directory: frontend 
      - run: npm run build
        working-directory: frontend
